name: 'Post-Integration: Prerelease Action'
description: 'Release action for post-integration'
author: 'sepulsa'
inputs:
  key:
    required: true
    description: 'JIRA issue key'
  token:
    required: true
    description: 'Github Personal Access Token with permission to delete environment'
runs:
  using: 'node12'
  main: 'dist/index.js'
